# Multivariate Linear Regression 


    1.Using sklearn
    2.Using Matrices and applying formula of least square solution
    



## 1. Using scikit-learn

Using functions of scikit-learn library, the data is used to train the regression and co-effecients are obtained and hence prediction for test case is obtained.

The following functions are used here:
* LinearRegression()
* fit()
* .coef_
* .intercept_

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("Admission_Predict.csv")
df = df.rename(columns = lambda x: x.strip())

In [5]:
xdf = df[['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research']]
ydf = df['Chance_of_admit']

In [6]:
reg = LinearRegression().fit(xdf, ydf)

In [7]:
reg.coef_

array([ 0.00173904,  0.00291492,  0.00578891, -0.00340745,  0.02243924,
        0.11873552,  0.0245213 ])

In [8]:
reg.intercept_

-1.2579141499830298

In [19]:
reg.predict([[333,117,4,5,4,9.66,1]])

array([0.92961153])

## 2.  Least Square Solution
    
For linear system Ax = b of m equations in n unknowns that are inconsistent, one looks for vectors 
that come as close as possible to being solutions in the sense that they minimize b − Ax
with respect to the 
**Euclidean inner product.**

If A is an m × n matrix with linearly independent column vectors,
then for every m × 1 matrix b, the linear system Ax = b has a unique least squares
solution. This solution is given by 
$$x = inv(((\mathbf{A}^\intercal)A ))\mathbf{A}^\intercal\ b\   $$       




c + $a_{0}$$x_{0}$ + $a_{0}$$x_{0}$ + $a_{0}$$x_{0}$ +.....+ $a_{0}$$x_{0}$ = b

where :
* c = constant
* $x_{0}$ ,$x_{1}$ ,$x_{2}$,....,$x_{n}$ are the independent variables
* b is the dependent variable

To convert the equation to the form Ax = b:
   1. Matrix A contains all the columns of dependent variable and an additional column of with value 1( to obtain the constant c), here columns are: 'const', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research'
   2. Matrix b contains the values of dependent variables, here the column is : Chance_of_admit
   3. Once the above matrices are obtained, we plug them in the formula of *least square solution* to get the matrix *x* and hence obtain the co-effecients.
   4. Once *x* is obtained,  *b* is calculated for a test case by matrix multiplication of A and *x*

NOTE -  We use the same test case i.e. the one used in method of sklearn and verify that same results are obtained in both approaches.
   


In [9]:
df['const'] = 1

In [10]:
Mdf = df[['const', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA', 'Research']]

In [11]:
Mdf = Mdf.to_numpy()

In [22]:
Mdf

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  1.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  1.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [  1.  , 325.  , 107.  , ...,   3.5 ,   9.11,   1.  ],
       [  1.  , 330.  , 116.  , ...,   4.5 ,   9.45,   1.  ],
       [  1.  , 312.  , 103.  , ...,   4.  ,   8.78,   0.  ]])

In [13]:
def get_v(M, y):
    M_t = M.transpose()
    I = np.linalg.inv(np.matmul(M_t , M))
    P = np.matmul(I, M_t)
    res = np.matmul(P, y)
    return res

In [14]:
v = get_v(Mdf, ydf)

In [15]:
v

array([-1.25791415,  0.00173904,  0.00291492,  0.00578891, -0.00340745,
        0.02243924,  0.11873552,  0.0245213 ])

In [24]:
test_c = [1,333,117,4,5,4,9.66,1]
A = np.asmatrix(test_c)
x = np.asmatrix(v)
b = np.matmul(A,v )
b

matrix([[0.92961153]])